jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    #App\Entity\User:
        #attributes:
          #id:
            #groups: ['gpshisto', 'user']